---
title: "Neighborhood_Effects_Applications"
author: "Andreas Petrou-Zeniou"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidyr)
library(dplyr)
library(quantreg)
library(haven)
library(readstata13)
library(fastDummies)
library(matrixcalc)
```

```{r}

df <- read.csv("Input_Data/tract_outcomes_simple.csv")
df_voucher <- read.csv("Input_Data/Housing_Choice_Vouchers_by_Tract.csv")

```

```{r}

cz_list <- c("Port St. Lucie", "Chicago", "Philadelphia", "New York", "Newark", "Milwaukee", "Atlanta", "St. Louis", "Cleveland", "Miami", "Detroit", "Pittsburgh", "Columbus", "Bridgeport", "Dallas", "Washington DC", "Austin", "Raleigh", "Cincinnati", "Charlotte", "Kansas City", "New Orleans", "Nashville", "Baltimore", "Buffalo", "Indianapolis", "Grand Rapids", "Dayton", "San Francisco", "Tampa", "Salt Lake City", "Boston", "Houston", "Phoenix", "Minneapolis", "Denver", "Los Angeles", "Jacksonville", "Fort Worth", "San Antonio", "Orlando", "San Jose", "Sacramento", "San Diego", "Manchester", "Providence", "Fresno", "Las Vegas", "Portland", "Seattle")

```

```{r}

df <- df %>% filter(czname %in% cz_list)
df_voucher <- df_voucher %>% 
  rename(state = STATE, county = COUNTY, tract = TRACT) %>%
  rename(voucher_rec = HCV_PUBLIC) %>%
  select(state, county, tract, voucher_rec)

df <- left_join(df, df_voucher, by=c("state", "county", "tract"))

```

```{r}

df <- df %>%
  select(c(czname, tract, kfr_pooled_pooled_p25, kfr_pooled_pooled_p25_se, pooled_pooled_count, voucher_rec)) %>%
  mutate(kfr_pooled_pooled_p25_var = kfr_pooled_pooled_p25_se ^ 2) %>%
  select(c(czname, tract, kfr_pooled_pooled_p25, kfr_pooled_pooled_p25_var, pooled_pooled_count, voucher_rec))

```

```{r}

for (cz in cz_list) {
  
  print(cz)
  
  df_temp <- df %>% filter(czname == cz)
  # df_temp <- df[sample(nrow(df_temp), 100), ]
  df_temp <- replace(df_temp, is.na(df_temp), 0)
  print(nrow(df_temp))
  
  print("A")
  
  X <- df_temp %>% select(kfr_pooled_pooled_p25) %>% as.matrix()
  
  Sd <- as.matrix(df_temp$kfr_pooled_pooled_p25_var)
  S <- matrix(0, nrow(df_temp), nrow(df_temp))
  
  diag(S) <- Sd
  
  print("A1")
  
  n_15 <- floor(nrow(df_temp) / 3)
  
  df_temp <- df_temp %>% mutate(voucher_rec = ifelse(is.na(voucher_rec),0,voucher_rec))
  
  N <- nrow(df_temp)
  
  pop <- sum(df_temp$voucher_rec)
  df_temp <- df_temp %>% mutate(voucher_rec = voucher_rec / pop)
  
  id_matrix <- as.vector(-1 * df_temp$voucher_rec)
  
  print("A2")
  
  for (row in (2:N)) {
    temp <- id_matrix
    id_matrix <- rbind(temp, as.vector(-1 * df_temp$voucher_rec))
  }
  
  diag(id_matrix) <- diag(id_matrix) + 1
  
  Id <- matrix(0, nrow = N, ncol = N)
  diag(Id) <- 1
  
  X2 <- rep(X, n_15)
  Y <- id_matrix %*% X
  S <- id_matrix %*% S %*% t(id_matrix)
  
  rank_list <- (1:n_15)
  
  write.csv(S, paste("Input_Data_Processed/Sigma_quantiles_neighborhood_",cz,".csv",sep=""))
  write.csv(X2, paste("Input_Data_Processed/X_quantiles_neighborhood_",cz,".csv",sep=""))
  write.csv(Y, paste("Input_Data_Processed/Y_quantiles_neighborhood_",cz,".csv",sep=""))
  write.csv(rank_list, paste("Input_Data_Processed/rank_quantiles_neighborhood_",cz,".csv",sep=""))
    
}

```
